version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

volumes:
  db_data:
