version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - /home/fran/docker/envs/backend_ainotege.env
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - /home/fran/docker/envs/frontend_ainotege.env
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
